### ISSUE TITLE
user-api - Faltam algumas classes

### ISSUE THREAD

**Issue by adornogomes** [ezambomsantana/java-back-end-livro#1]
Olá,

Algumas classes do projeto "user-api" importam classes inexistentes:

import com.santana.java.back.end.dto.UserDTO;
import com.santana.java.back.end.exception.advice.UserNotFoundException;
import com.santana.java.back.end.dto.ErrorDTO;
import com.santana.java.back.end.exception.UserNotFoundException;

Poderia me ajudar com esta questão, por favor?

**Comment by ezambomsantana** [comment]
Olá,

essas classes estão no projeto shopping-client.
